[package]
name = "aoc2015"
version = "0.1.0"
authors = ["Alexey Filippov <alexey@filippov.uk>"]
edition = "2015"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
md5 = "0.7.0"
bit-vec = "0.6.3"
itertools = "0.11.0"
